// <auto-generated />
namespace Instagram_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class createdReactTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createdReactTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202204262205048_createdReactTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
